parameters:
    env(ASDORIA_MESSENGER_TRANSPORT_BULK_EDIT_DSN): 'doctrine://default'
    env(ASDORIA_MESSENGER_TRANSPORT_BULK_EDIT_FAILED_DSN): 'doctrine://default?queue_name=asdoria_bulk_edit_failed'
    asdoria_messenger_transport_bulk_edit_dsn: '%env(resolve:ASDORIA_MESSENGER_TRANSPORT_BULK_EDIT_DSN)%'
    asdoria_messenger_transport_bulk_edit_failed_dsn: '%env(resolve:ASDORIA_MESSENGER_TRANSPORT_BULK_EDIT_FAILED_DSN)%'
imports:
    - { resource: "grids/*.yaml" }

sylius_ui:
    events:
        asdoria_bulk_edit.admin.index.javascripts:
            blocks:
                scripts:
                    template: "@AsdoriaSyliusBulkEditPlugin/Admin/_javascripts.html.twig"
                    priority: 10
        asdoria_bulk_edit.admin.index.stylesheets:
            blocks:
                scripts:
                    template: "@AsdoriaSyliusBulkEditPlugin/Admin/_stylesheets.html.twig"
                    priority: 10

framework:
    assets:
        packages:
            asdoria_sylius_bulk_edit_plugin:
                base_path: '/bundles/asdoriasyliusbulkeditplugin'
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            asdoria_bulk_edit:
                dsn: '%asdoria_messenger_transport_bulk_edit_dsn%'
                failure_transport: 'asdoria_bulk_edit_failed'
            asdoria_bulk_edit_failed:
                dsn: '%asdoria_messenger_transport_bulk_edit_failed_dsn%'
        routing:
            # route all messages that extend this example base class or interface
            'Asdoria\SyliusBulkEditPlugin\Message\BulkEditNotificationInterface': asdoria_bulk_edit
        buses:
            asdoria_bulk_edit.bus:
                middleware:
                    # each time a message is handled, the Doctrine connection
                    # is "pinged" and reconnected if it's closed. Useful
                    # if your workers run for a long time and the database
                    # connection is sometimes lost
                    - doctrine_ping_connection
                    # After handling, the Doctrine connection is closed,
                    # which can free up database connections in a worker,
                    # instead of keeping them open forever
                    - doctrine_close_connection
                    # wraps all handlers in a single Doctrine transaction
                    # handlers do not need to call flush() and an error
                    # in any handler will cause a rollback
                    - doctrine_transaction

